### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by mxmeinhold** [rit-ai/ritai-bot#1]
It's difficult to deploy this application without a statement of its dependencies. A requirements.txt would allow for installing via pip -r as is a standard in some deployment schemes, as well as making it simple for contributors to specify package versioning for stability.

**Comment by pgalatic** [comment]
Added requirements.txt

Thanks mom 💋

**Comment by mxmeinhold** [comment]
You're welcome ❤️
